// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX9BEuoEJbA4qzasW75KGUxNW5FIz_wi4',
    appId: '1:350923056016:web:33d55c48f43b53d8ba4915',
    messagingSenderId: '350923056016',
    projectId: 'mad-hw4-8f367',
    authDomain: 'mad-hw4-8f367.firebaseapp.com',
    storageBucket: 'mad-hw4-8f367.firebasestorage.app',
    measurementId: 'G-HD4H32VDMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9vA4e-yHGu9vz7YV3NKzDo94XbJp1Pgc',
    appId: '1:350923056016:android:179b8a8b708c49a4ba4915',
    messagingSenderId: '350923056016',
    projectId: 'mad-hw4-8f367',
    storageBucket: 'mad-hw4-8f367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgcyrncMl2a3v6gZpJ1JybT6l1JG_u_2E',
    appId: '1:350923056016:ios:ad0cabbfcf296877ba4915',
    messagingSenderId: '350923056016',
    projectId: 'mad-hw4-8f367',
    storageBucket: 'mad-hw4-8f367.firebasestorage.app',
    iosBundleId: 'com.example.madHw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgcyrncMl2a3v6gZpJ1JybT6l1JG_u_2E',
    appId: '1:350923056016:ios:ad0cabbfcf296877ba4915',
    messagingSenderId: '350923056016',
    projectId: 'mad-hw4-8f367',
    storageBucket: 'mad-hw4-8f367.firebasestorage.app',
    iosBundleId: 'com.example.madHw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX9BEuoEJbA4qzasW75KGUxNW5FIz_wi4',
    appId: '1:350923056016:web:5514da933beacdeaba4915',
    messagingSenderId: '350923056016',
    projectId: 'mad-hw4-8f367',
    authDomain: 'mad-hw4-8f367.firebaseapp.com',
    storageBucket: 'mad-hw4-8f367.firebasestorage.app',
    measurementId: 'G-0GJPMJWC83',
  );
}
